platform: linux
image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse
    tag: latest
inputs:
- name: repo
- name: utils
outputs:
- name: releases
caches:
- path: repo/blobs
- path: repo/.blobs
run:
  path: bash
  args:
  - -c
  - |
    find repo/blobs
    find repo/.blobs
    utils/scripts/bosh-create-release.sh
