platform: linux
image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse
    tag: latest
inputs:
- name: releases
- name: repo-version
- name: utils
run:
  path: bash
  args:
  - -c
  - |
    utils/tasks/boshrelease-upload-dev-to-nexus.sh
