platform: linux
image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse
    tag: latest
inputs:
- name: repo
- name: utils
outputs:
- name: releases
caches:
- path: ~/.bosh
run:
  path: bash
  args:
  - -c
  - |
    pwd
    ls -la
    bash utils/scripts/bosh-create-release.sh
