platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.5-jdk-8
inputs:
  - name: repo-version
  - name: repo-staging
  - name: repo-prod
  - name: utils
  - name: m2
outputs:
  - name: release-out
run:
  path: bash
  args:
    - utils/tasks/bump-to-next-develop-version.sh
