platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.5-jdk-8
inputs:
  - name: repo
  - name: utils
  - name: m2
outputs:
  - name: output
run:
  path: bash
  args:
  - -c
  - |
    utils/scripts/add-repos-in-pom-xml.sh repo && \
    utils/scripts/create-m2-rootfs.sh